#include "offloading_macros.h"
MODULE UTIL_WW_MOD

USE YOMT1, ONLY : WW



INTERFACE COPY
MODULE PROCEDURE COPY_WW
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_WW
END INTERFACE



CONTAINS





SUBROUTINE COPY_WW (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_UU2_MOD
IMPLICIT NONE
TYPE (WW), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  GPU_DATA_ALLOC(SELF)
  GPU_UPDATE_DEVICE(SELF)
ENDIF
DO J1 = LBOUND (SELF%UU, 1), UBOUND (SELF%UU, 1)
  CALL COPY_UU2 (SELF%UU (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
ENDDO

END SUBROUTINE



     



SUBROUTINE WIPE_WW (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_UU2_MOD
IMPLICIT NONE
TYPE (WW), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
DO J1 = LBOUND (SELF%UU, 1), UBOUND (SELF%UU, 1)
  CALL WIPE_UU2 (SELF%UU (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
ENDDO

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  GPU_DATA_DELETE(SELF)
ENDIF
END SUBROUTINE



END MODULE
