#include "offloading_macros.h"
MODULE UTIL_TT_MOD

USE YOMT1, ONLY : TT



INTERFACE COPY
MODULE PROCEDURE COPY_TT
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_TT
END INTERFACE



CONTAINS





SUBROUTINE COPY_TT (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LY

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  GPU_DATA_ALLOC(SELF)
  GPU_UPDATE_DEVICE(SELF)
ENDIF

LY = ASSOCIATED (SELF%Y)
IF (LY) THEN
  GPU_DATA_ALLOC(SELF%Y)
  GPU_UPDATE_DEVICE(SELF%Y)
  GPU_DATA_ATTACH(SELF%Y)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_TT (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LY

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LY = ASSOCIATED (SELF%Y)
IF (LY) THEN
  GPU_DATA_DETACH(SELF%Y)
  GPU_DATA_DETACH(SELF%Y)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  GPU_DATA_DELETE(SELF)
ENDIF
END SUBROUTINE



END MODULE
