MODULE UTIL_VV_MOD

USE YOMT1, ONLY : VV



INTERFACE COPY
MODULE PROCEDURE COPY_VV
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_VV
END INTERFACE



CONTAINS





SUBROUTINE COPY_VV (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_UU_MOD
IMPLICIT NONE
TYPE (VV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LUU2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL COPY_UU (SELF%UU1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LUU2 = ASSOCIATED (SELF%UU2)
IF (LUU2) THEN
  !$ACC ENTER DATA CREATE (SELF%UU2)
  !$ACC UPDATE DEVICE (SELF%UU2)
  CALL COPY_UU (SELF%UU2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (SELF%UU2)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_VV (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_UU_MOD
IMPLICIT NONE
TYPE (VV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LUU2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_UU (SELF%UU1, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LUU2 = ASSOCIATED (SELF%UU2)
IF (LUU2) THEN
  !$ACC EXIT DATA DETACH (SELF%UU2)
  CALL WIPE_UU (SELF%UU2, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (SELF%UU2)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
