#include "offloading_macros.h"
MODULE UTIL_UU_MOD

USE YOMT1, ONLY : UU



INTERFACE COPY
MODULE PROCEDURE COPY_UU
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_UU
END INTERFACE



CONTAINS





SUBROUTINE COPY_UU (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (UU), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LD

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  GPU_DATA_ALLOC(SELF)
  GPU_UPDATE_DEVICE(SELF)
ENDIF

LD = ALLOCATED (SELF%D)
IF (LD) THEN
  GPU_DATA_ALLOC(SELF%D)
  GPU_UPDATE_DEVICE(SELF%D)
  GPU_DATA_ATTACH(SELF%D)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_UU (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (UU), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LD

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LD = ALLOCATED (SELF%D)
IF (LD) THEN
  GPU_DATA_DETACH(SELF%D)
  GPU_DATA_DETACH(SELF%D)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  GPU_DATA_DELETE(SELF)
ENDIF
END SUBROUTINE



END MODULE
