#include "offloading_macros.h"
MODULE UTIL_VV_MOD

USE YOMT1, ONLY : VV



INTERFACE COPY
MODULE PROCEDURE COPY_VV
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_VV
END INTERFACE



CONTAINS





SUBROUTINE COPY_VV (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_UU_MOD
IMPLICIT NONE
TYPE (VV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LUU2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  GPU_DATA_ALLOC(SELF)
  GPU_UPDATE_DEVICE(SELF)
ENDIF

CALL COPY_UU (SELF%UU1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LUU2 = ASSOCIATED (SELF%UU2)
IF (LUU2) THEN
  GPU_DATA_ALLOC(SELF%UU2)
  GPU_UPDATE_DEVICE(SELF%UU2)
  CALL COPY_UU (SELF%UU2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  GPU_DATA_ATTACH(SELF%UU2)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_VV (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_UU_MOD
IMPLICIT NONE
TYPE (VV), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LUU2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL WIPE_UU (SELF%UU1, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LUU2 = ASSOCIATED (SELF%UU2)
IF (LUU2) THEN
  GPU_DATA_DETACH(SELF%UU2)
  CALL WIPE_UU (SELF%UU2, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  GPU_DATA_DETACH(SELF%UU2)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  GPU_DATA_DELETE(SELF)
ENDIF
END SUBROUTINE



END MODULE
